---
- name: Install Prometheus and Grafana on control node
  hosts: control
  become: true
  vars_files:
    - vars.yml
  tasks:

    - name: Download Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v3.1.0/prometheus-3.1.0.linux-amd64.tar.gz"
        dest: "/tmp/prometheus-3.1.0.linux-amd64.tar.gz"

    - name: Extract Prometheus
      unarchive:
        src: "/tmp/prometheus-3.1.0.linux-amd64.tar.gz"
        dest: "/usr/local/bin/"
        remote_src: yes

    - name: Create Prometheus user
      user:
        name: prometheus
        shell: /bin/false
        state: present

    - name: Create Prometheus directories
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
      with_items:
        - /etc/prometheus
        - /var/lib/prometheus

    - name: Move Prometheus binaries
      command: "mv /usr/local/bin/prometheus-3.1.0.linux-amd64/prometheus /usr/local/bin/prometheus"
    
    - name: Move Prometheus tool
      command: "mv /usr/local/bin/prometheus-3.1.0.linux-amd64/promtool /usr/local/bin/promtool"

    - name: Create Prometheus configuration file
      copy:
        dest: "/etc/prometheus/prometheus.yml"
        content: |
          global:
            scrape_interval: 15s
            evaluation_interval: 15s
          
          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']
        
            - job_name: 'nodes'
              static_configs:
                - targets:
                  {% for ip in prometheus_nodes %}
                  - '{{ ip }}:9100'
                  {% endfor %}

    - name: Create Prometheus service file
      copy:
        dest: "/etc/systemd/system/prometheus.service"
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target
          
          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
            --config.file=/etc/prometheus/prometheus.yml \
            --storage.tsdb.path=/var/lib/prometheus/ \
            --web.console.templates=/etc/prometheus/consoles \
            --web.console.libraries=/etc/prometheus/console_libraries

          [Install]
          WantedBy=multi-user.target
     
      register: prometheus_service_status
      ignore_errors: yes
    - name: Check if Prometheus service is running
      command: systemctl is-active prometheus
      register: prometheus_status
      changed_when: false
      ignore_errors: true

    - name: Manage Prometheus service state
      systemd:
        name: prometheus
        state: "{{ 'restarted' if prometheus_status.rc == 0 else 'started' }}"
        enabled: yes
        
    - name: Add Grafana GPG key and repository
      shell: |
        sudo mkdir -p /etc/apt/keyrings/
        wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/grafana.gpg > /dev/null
        echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" | sudo tee /etc/apt/sources.list.d/grafana.list
        sudo apt-get update

    - name: Install Grafana
      apt:
        name: grafana
        state: present

    - name: Start Grafana service
      systemd:
        name: grafana-server
        state: started
        enabled: yes